# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhRbxCZsCjU_KMUgIE7e8be-I4lliApF

## 1. Split this string
"""



"""# Basic Python"""

s = "Hi there Sam!"

s='Hi there sam!'

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("the diameter of Earth is 12742 kilometers")

"""## 3. In this nest dictionary grab the word "hello"
"""

d1 = {'simple_key':'hello'}
d2 = {'k1':{'k2':'hello'}}
d3 = {'k1':[{'nest_key':['this is deep',['hello']]}]}

print('hello')

"""# Numpy"""

import numpy as np

a=np.array

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

array=np.zeros(10)

array=np.ones(10)*5

print("An array of 10 zeros:")

print("An array of 10 fives:")

"""## 5. Create an array of all the even integers from 20 to a35"""

print("Array of all the even integer from 20 to 35")

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

np.arange(0,9)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a=np.array([1,2,3])
b=np.array([4,5,6])
print =a,b

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

# format
# ufo.loc[rows, columns]

# row 3, 2 columns

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
 
# initializing K
K = 41
 
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

import pandas as pd  
      
# List1  
lst = [['1', 'aaa', 22], ['2', 'bbb', 25], 
       ['3', 'ccc', 24]] 
      
df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],
                                           dtype = float) 
print(df)

